# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cerveau.channels:
        - '%env(CERVEAU_STREAMER)%'
    cerveau.badWords:
        - 'Buy followers, primes and viewers'
        - 'bigfollows . com'
        - 'stearncomminuty'
    cerveau.superUsers: '%env(json:CERVEAU_SUPER_USERS)%'
    cerveau.streamer.nickname: '%env(CERVEAU_STREAMER)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $streamer: '%cerveau.streamer.nickname%'

    _instanceof:
        \Cerveau\CommandHandler\CommandHandlerInterface:
            tags: ['cerveau.command']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Entity/'
            - '../src/App/Kernel.php'

    Cerveau\:
        resource: '../src/Cerveau'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    GhostZero\Tmi\Client:
        factory: ['@Cerveau\IRCClientFactory', 'createClient']

    Symfony\Component\Cache\Adapter\FilesystemAdapter: ~

    Cerveau\CommandDispatcher:
        arguments:
            $commandSymbols: ['!']
        calls:
            - setCommands:
                $commands: !tagged_iterator cerveau.command

    Cerveau\CommandHandler\ResponseCommandHandler:
        arguments:
            $responses:
                ping: Pong!
                github: https://github.com/nelyntu/Cerveau
                lurk: You have said the magick word to make yourself invisible to all eyes upon you, allowing you to fade into the shadows.
                return: You have rolled a Nat 1, clearing your invisibility buff from earlier. You might want to roll for initiative…

    Cerveau\IRCClientFactory:
        arguments:
            $channels: '%cerveau.channels%'
            $nick: '%cerveau.streamer.nickname%'
            $secret: "%env(CERVEAU_TWITCH_OAUTH)%"

    Cerveau\Bot:
        arguments:
            $options:
                badwords: '%cerveau.badWords%'
                channels: '%cerveau.channels%'
                nick: '%cerveau.streamer.nickname%'
                secret: "%env(CERVEAU_TWITCH_OAUTH)%"

    Cerveau\UserList:
        arguments:
            $superUsers: '%cerveau.superUsers%'
