Cerveau\Entity\ChatEvent:
  type: entity
  table: chat_event
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    channel:
      type: string
      nullable: false
    createdAt:
      type: datetime_immutable
      nullable: false
    type:
      type: string
      nullable: false
    data:
      type: json
      nullable: false
  manyToOne:
    user:
      targetEntity: Cerveau\Entity\User
